# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
  port: 8080
  servlet:
    context-path: /shiro-test

spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  freemarker:
          request-context-attribute: request
          allow-request-override: false
          cache: false
          check-template-location: true
          charset: UTF-8
          content-type: text/html; charset=utf-8
          expose-request-attributes: false
          expose-session-attributes: false
          expose-spring-macro-helpers: false
          #suffix: .html
          template-loader-path: classpath:/templates
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static
  session:
    timeout: 7200

#shiro配置
shiro:
  loginUrl: /toLogin




